export const AllJamoalar = [
    {
        id: 4,
        name: "2005(1)",
        Orin: 1,
        img: "https://ir.ozone.ru/s3/multimedia-9/6623358309.jpg",
        oyin: "5",
        achko: "10",
        gollar: "22",
        HammaSariq: "0",
        HammaQizil: "0",
        Tuzulishi: "../src/assets/2005_positsion_graphic.jpg",
        Players: [
            {
                name: "Asatbek",
                Age: "19",
                Position: "Defender",
            },
            {
                name: "Kamronbek",
                Age: "19",
                Position: "Defender",
            },
            {
                name: "Oqilbek",
                Age: "19",
                Position: "Forward",
            },
            {
                name: "Mirjaxon",
                captain: "Sardor",
                Age: "19",
                Position: "Goalkeapper",
            },
            {
                name: "Rasulbek",
                Age: "19",
                Position: "Forward",
            },
            {
                name: "Bunyodbek",
                Age: "19",
                Position: "Forward",
            },
            {
                name: "Shamshodbek",
                Age: "18",
                Position: "Midfielder",
            },
            {
                name: "IZZATBEK",
                Age: "?",
                Position: "Midfielder",
            },
            {
                name: "Bobomurod",
                Age: "19",
                Position: "Midfielder",
            },
            {
                name: "Dilmurod",
                Age: "19",
                Position: "Forward",
            },
            {
                name: "Jasurbek",
                Age: "19",
                Position: "Midfielder",
            },
            {
                name: "Alibek",
                Age: "19",
                Position: "Forward",
            },
        ],
    },
    {
        id: 3,
        name: "2006(1)",
        Orin: 2,
        img: "http://s3-eu-west-1.amazonaws.com/product-img/75319_maxi_0.jpg",
        oyin: "5",
        achko: "7",
        gollar: "24",
        HammaSariq: "1",
        HammaQizil: "0",
        Tuzulishi: "../src/assets/POSITSION.jpg",
        Players: [
            {
                name: "Ozodbek",
                Age: "18",
                Position: "Defender",
            },
            {
                name: "Ismoil",
                Age: "18",
                Position: "Defender",
            },
            {
                name: "Dovudbek",
                Age: "18",
                Position: "Forward",
            },
            {
                name: "Nurbek",
                Age: "18",
                Position: "Goalkeapper",
            },
            {
                name: "Nodirbek",
                captain: "Sardor",
                Age: "18",
                Position: "Defender",
                Sariq: "https://e1.365dm.com/score-centre/icons/yellow_card.svg"
            },
            {
                name: "Shoxrux",
                Age: "18",
                Position: "Forward",
            },
            {
                name: "Asadbek",
                Age: "18",
                Position: "Forward",
            },
            {
                name: "Barkamol",
                Age: "18",
                Position: "Forward",
            },
            {
                name: "Shoxjaxon",
                Age: "18",
                Position: "GoalKeapper",
            },
            {
                name: "Jaxongir",
                Age: "18",
                Position: "GoalKeapper",
            },
        ],
    },
    {
        id: 6,
        name: "2006(2)",
        Orin: 3,
        img: "https://avatars.mds.yandex.net/i?id=9714adecfb06c39800522a12b51b6dd827446861-12542244-images-thumbs&n=13",
        oyin: "5",
        achko: "7",
        gollar: "22",
        HammaSariq: "1",
        HammaQizil: "0",
        Tuzulishi: "../src/assets/2006(2)_positsion_graphic.jpg",
        Players: [
            {
                name: "Ozodbek",
                Age: "18",
                Position: "Defender",
            },
            {
                name: "Beksulton",
                Age: "18",
                Position: "Defender",
            },
            {
                name: "Nurmuhammad",
                Age: "18",
                Position: "Forward",
                Sariq: "https://e1.365dm.com/score-centre/icons/yellow_card.svg"
            },
            {
                name: "Hasanboy",
                Age: "18",
                Position: "Goalkeapper",
            },
            {
                name: "Azamat",
                captain: "Sardor",
                Age: "18",
                Position: "Forward",
            },
            {
                name: "Jasurbek",
                Age: "?",
                Position: "Forward",
            },
            {
                name: "Asadbek",
                Age: "18",
                Position: "Midfielder",
            },
        ],
    },
    {
        id: 2,
        name: "2007(1)",
        Orin: 4,
        img: "https://avatars.mds.yandex.net/i?id=b78c3c2149b01d357fe7f836840996a1a523fd5d-4825158-images-thumbs&n=13",
        oyin: "4",
        achko: "6",
        gollar: "18",
        HammaSariq: "0",
        HammaQizil: "0",
        Tuzulishi: "../src/assets/2007_positsion_graphic.jpg",
        Players: [
            {
                name: "Mirzadavlat",
                Age: "17",
                Position: "GoalKeapper",
            },
            {
                name: "Akmal",
                Age: "17",
                Position: "Defender",
            },
            {
                name: "Mirziyod",
                Age: "17",
                Position: "Forward",
            },
            {
                name: "Husanboy",
                Age: "17",
                Position: "Midfielder",
            },
            {
                name: "Javoxir",
                captain: "Sardor",
                Age: "17",
                Position: "Forward",
            },
            {
                name: "Asadbek",
                Age: "17",
                Position: "Forward",
            },
            {
                name: "Shoxjahon",
                Age: "17",
                Position: "Midfielder",
            },
            {
                name: "Shaxriyor",
                Age: "17",
                Position: "Midfielder",
            },
        ],

    },
    {
        id: 5,
        name: "2000(1)",
        Orin: 5,
        img: "https://cdn.shopify.com/s/files/1/0518/3432/3098/products/Milanlogomockupfuljpeg.jpg?v=1659529798",
        oyin: "4",
        achko: "6",
        gollar: "15",
        HammaSariq: "0",
        HammaQizil: "0",
        Tuzulishi: "../src/assets/2000_positsion_graphic.jpg",
        Players: [
            {
                name: "Muhammadqodir",
                Age: "22",
                Position: "Defender",
            },
            {
                name: "Bunyodbek",
                Age: "22",
                Position: "Defender",
            },
            {
                name: "Sharofiddin",
                Age: "22",
                Position: "Forward",
            },
            {
                name: "Abdulaziz",
                Age: "22",
                Position: "Goalkeapper",
            },
            {
                name: "Dostonbek",
                captain: "Sardor",
                Age: "22",
                Position: "Defender",
            },
        ],
    },
    {
        id: 1,
        name: "2008(1)",
        Orin: 6,
        img: "https://i.pinimg.com/originals/a8/1a/72/a81a7215b02f6a9a6b5b1b28d2f2882f.png",
        oyin: "5",
        achko: "4",
        gollar: "9",
        HammaSariq: "0",
        HammaQizil: "0",
        Tuzulishi: "../src/assets/2008_positsion_graphic.jpg",
        Players: [
            {
                name: "Lazizbek",
                Age: "16",
                Position: "Defender",
            },
            {
                name: "Mirihtiyor",
                Age: "16",
                Position: "Defender",
            },
            {
                name: "Akobir",
                Age: "16",
                Position: "Forward",
            },
            {
                name: "Sardorbek",
                Age: "16",
                Position: "Goalkeapper",
            },
            {
                name: "Mirshohid",
                captain: "Sardor",
                Age: "16",
                Position: "Forward",
            },
        ],
    },
]